package stringsE

// 389. Find the Difference
// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.
// link - https://leetcode.com/problems/find-the-difference/
func findTheDifference(s string, t string) byte {
	first := make(map[string]int)
	for _, char := range s {
		first[string(char)]++
	}
	for _, char := range t {
		if _, ok := first[string(char)]; !ok {
			return byte(char)
		} else {
			first[string(char)]--
			if first[string(char)] < 0 {
				return byte(char)
			}
		}
	}
	return 0
}
